version: 2

jobs:
  build:
    working_directory: ~/build
    docker:
      - image: docksal/bitbucket-pipelines-agent:edge
    steps:
      - checkout
      - run: pwd
      - run: ls -la
      - run: whoami
      - run: env
      - run: cat $HOME/.circlerc
      - run:
          name: Configure build environment
          command: |
            build-env
            echo "export DOCKER_HOST=localhost:2374" >> $HOME/.circlerc
            echo "export DOMAIN=drupal8.${DOCKSAL_HOST}" >> $HOME/.circlerc
            echo "export COMPOSE_PROJECT_NAME_SAFE=drupal8" >> $HOME/.circlerc
      - run: env
      - run:
          name: Check Docker
          command: |
            docker version
      - run:
          name: Deploy sandbox
          command: |
            docker stack deploy --compose-file .docksal/stack.yml "$COMPOSE_PROJECT_NAME_SAFE"
