version: 2

jobs:
  build:
    working_directory: /home/agent/build
    docker:
      - image: docksal/bitbucket-pipelines-agent:edge
    environment:
       BASH_ENV: /home/agent/.bashrc
    steps:
      - checkout
      - run:
          name: Configure build environment
          command: |
            touch $BASH_ENV
            echo 'source build-env' >> $BASH_ENV
      - run: env
      - run:
          name: Check Docker
          command: |
            docker version
      - run:
          name: Deploy sandbox
          command: |
            docker stack deploy --compose-file .docksal/stack.yml "DOCKER_STACK_NAME"
